// Mock data matching the shared/src/recipe.ts shape from the source codebase.
window.MOCK_USER = {
  uid: "u_jess",
  displayName: "Jess Marks",
  email: "jess@marksfamily.test",
};

window.MOCK_CHAPTERS = [
  "appetizer",
  "soup",
  "salad",
  "side",
  "entree",
  "sauce",
  "dessert",
];

window.MOCK_RECIPES = [
  {
    id: "r1",
    title: "Buttermilk pancakes",
    category: "entree",
    tags: ["vegetarian", "weekend", "kids"],
    photo: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800&h=600&fit=crop&q=80",
    source: { type: "url", url: "https://cooking.nytimes.com/recipes/12317-pancakes" },
    yield: "4 servings",
    prepTime: "20 min",
    cookTime: "8 min",
    totalTime: "28 min",
    ingredients: [
      { heading: null, items: [
        "2 cups all-purpose flour",
        "2 tablespoons sugar",
        "2 teaspoons baking powder",
        "½ teaspoon baking soda",
        "½ teaspoon kosher salt",
        "2 cups buttermilk",
        "2 large eggs",
        "3 tablespoons unsalted butter, melted",
      ]},
    ],
    instructions: [
      { heading: null, items: [
        "Whisk the dry ingredients together in a large bowl.",
        "In another bowl, whisk the buttermilk, eggs, and melted butter.",
        "Pour the wet into the dry and fold gently — lumps are fine.",
        "Heat a griddle to medium. Butter lightly.",
        "Pour ¼-cup portions; flip when the bubbles set. Serve immediately.",
      ]},
    ],
    notes: "If the batter feels too thick, splash in a little more buttermilk. The lumpier the better.",
  },
  {
    id: "r2",
    title: "Roast chicken with lemon and thyme",
    category: "entree",
    tags: ["sunday", "comfort"],
    photo: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=600&fit=crop&q=80",
    source: { type: "book", title: "Salt, Fat, Acid, Heat", author: "Samin Nosrat", page: "232" },
    yield: "4 servings",
    prepTime: "15 min",
    cookTime: "1 hr",
    totalTime: "1 hr 15 min",
    ingredients: [
      { heading: "Chicken", items: [
        "1 whole chicken, 3½ to 4 lb",
        "1 tablespoon kosher salt",
        "1 lemon, halved",
        "6 sprigs fresh thyme",
        "2 tablespoons olive oil",
      ]},
      { heading: "Pan sauce", items: [
        "½ cup dry white wine",
        "1 cup chicken stock",
        "1 tablespoon cold butter",
      ]},
    ],
    instructions: [
      { heading: "Day before", items: [
        "Salt the chicken inside and out. Refrigerate uncovered overnight.",
      ]},
      { heading: "Roast", items: [
        "Heat oven to 220°C (425°F).",
        "Stuff the cavity with lemon and thyme. Truss the legs.",
        "Roast 50–60 min until a thermometer in the thigh reads 70°C.",
        "Rest on a board for 15 min before carving.",
      ]},
    ],
    notes: "Save the carcass for stock.",
  },
  {
    id: "r3",
    title: "Mom's lasagna",
    category: "entree",
    tags: ["family", "weekday", "freezer"],
    yield: "8 servings",
    prepTime: "45 min",
    cookTime: "1 hr",
    totalTime: "2 hr",
    ingredients: [
      { heading: null, items: [
        "1 lb lasagna noodles",
        "2 lb ground beef",
        "1 jar marinara",
        "32 oz ricotta",
        "1 lb mozzarella, shredded",
      ]},
    ],
    instructions: [
      { heading: null, items: [
        "Boil the noodles.",
        "Brown the beef and mix with marinara.",
        "Layer noodles, beef, ricotta, mozzarella. Repeat.",
        "Bake at 190°C for 45 min, then broil 5 min for the top.",
      ]},
    ],
  },
  {
    id: "r4",
    title: "Tomato soup",
    category: "soup",
    tags: ["vegetarian", "weekday", "freezer"],
    photo: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&h=600&fit=crop&q=80",
    yield: "6 servings",
    prepTime: "10 min",
    cookTime: "30 min",
    totalTime: "40 min",
    ingredients: [
      { heading: null, items: [
        "2 cans whole tomatoes",
        "1 onion, diced",
        "4 cloves garlic",
        "2 cups stock",
        "1 cup cream",
        "basil",
      ]},
    ],
    instructions: [
      { heading: null, items: [
        "Sweat onion and garlic in butter.",
        "Add tomatoes and stock. Simmer 20 min.",
        "Blend until smooth, stir in cream.",
        "Salt to taste. Tear basil over the top.",
      ]},
    ],
  },
  {
    id: "r5",
    title: "Caesar salad",
    category: "salad",
    tags: ["weekday"],
    photo: "https://images.unsplash.com/photo-1551248429-40975aa4de74?w=800&h=600&fit=crop&q=80",
    yield: "4 servings",
    ingredients: [{ heading: null, items: [
      "1 head romaine",
      "shaved parmesan",
      "croutons",
      "anchovy",
      "garlic",
      "lemon",
      "egg yolk",
    ]}],
    instructions: [{ heading: null, items: [
      "Whisk dressing.",
      "Toss with torn romaine.",
      "Top with parm and croutons.",
    ]}],
  },
  {
    id: "r6",
    title: "Roasted brussels sprouts",
    category: "side",
    tags: ["vegetarian", "thanksgiving"],
    yield: "6 servings",
    cookTime: "25 min",
    ingredients: [{ heading: null, items: [
      "1 lb brussels sprouts, halved",
      "olive oil",
      "balsamic",
      "salt",
    ]}],
    instructions: [{ heading: null, items: [
      "Heat oven to 220°C.",
      "Toss sprouts in oil and salt. Roast cut-side down 20 min.",
      "Finish with balsamic.",
    ]}],
  },
  {
    id: "r7",
    title: "Chocolate olive oil cake",
    category: "dessert",
    tags: ["vegetarian", "birthday"],
    photo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&h=600&fit=crop&q=80",
    source: { type: "url", url: "https://www.nigella.com/recipes/chocolate-olive-oil-cake" },
    yield: "8 servings",
    prepTime: "15 min",
    cookTime: "45 min",
    ingredients: [{ heading: null, items: [
      "150 ml olive oil",
      "50 g cocoa",
      "200 g sugar",
      "150 g ground almonds",
      "3 eggs",
    ]}],
    instructions: [{ heading: null, items: [
      "Sift cocoa into hot water.",
      "Whisk eggs and sugar; add olive oil.",
      "Fold in dry. Pour into a 9-inch pan.",
      "Bake at 170°C for 40–45 min.",
    ]}],
  },
  {
    id: "r8",
    title: "Bruschetta",
    category: "appetizer",
    tags: ["summer", "vegetarian"],
    photo: "https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=800&h=600&fit=crop&q=80",
    yield: "8 pieces",
    ingredients: [{ heading: null, items: [
      "ripe tomatoes",
      "garlic",
      "basil",
      "olive oil",
      "country bread",
    ]}],
    instructions: [{ heading: null, items: [
      "Dice tomatoes and salt them.",
      "Toast bread and rub with garlic.",
      "Spoon tomatoes on top with basil and a glug of oil.",
    ]}],
  },
];
